<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.linkcar.user</groupId>
        <artifactId>linkcar-user</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>user-api</artifactId>

    <dependencies>
        <!-- 内部依赖开始 -->
        <dependency>
            <groupId>com.linkcar.common</groupId>
            <artifactId>linkcar-common</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <!-- 内部依赖结束 -->
        <!-- 引用Feign声明性Rest客户端 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <!-- 引用swagger -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
        </dependency>
        <!-- 引用lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>